<a href="https://colab.research.google.com/github/DimosTheocharis/PytorchTutorial/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

In [2]:
my_list = [1, 2, 3, 4, 5]
print(my_list)

[1, 2, 3, 4, 5]


# **Numpy Arrays**

In [11]:
np1 = np.random.rand(3, 4)
print(np1)
print(np1.dtype)

[[0.30392879 0.1510592  0.502371   0.22989363]
 [0.2155446  0.35142433 0.04600435 0.89426922]
 [0.01676102 0.77775557 0.43699223 0.63601028]]
float64


# **Tensors**

In [17]:
tensor1 = torch.randn(3, 4)
print(tensor1)
print(tensor1.ndim)

tensor([[-0.2374,  0.6458,  0.2226, -0.7882],
        [-1.3323,  0.0214,  0.1291, -0.0799],
        [ 0.3249, -0.5242, -1.8356, -1.1622]])
2


In [18]:
tensor2 = torch.zeros(2, 3, 4)
print(tensor2)
print(tensor2.dtype)
print(tensor2.ndim)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
torch.float32
3


In [14]:
# Create tensor from numpy array
tensor3 = torch.tensor(np1)
print(tensor3)
print(tensor3.shape)

tensor([[0.3039, 0.1511, 0.5024, 0.2299],
        [0.2155, 0.3514, 0.0460, 0.8943],
        [0.0168, 0.7778, 0.4370, 0.6360]], dtype=torch.float64)
torch.Size([3, 4])
